# app/models.py
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


class FileType(str, Enum):
    """Enum for file types"""
    PUBLIC = "public"
    STUDENT = "student"
    TEACHER = "teacher"
    ADMIN = "admin"


class UserInfo(BaseModel):
    """User information for query logging (unified for students and teachers)"""
    user_id: int = Field(..., description="User ID from database")
    user_type: str = Field(default="Unknown", description="User type (e.g., 'Học sinh', 'Giáo viên')")
    department_id: Optional[int] = Field(None, description="Department ID")
    department_name: Optional[str] = Field(None, description="Department name for easier analytics")
    code: Optional[str] = Field(None, description="Student code or Teacher code (e.g., 'K21.YDUOC.001' or 'T.NNA.103')")
    years: Optional[int] = Field(None, description="Student year (1-5) or Teaching years, calculated from enrollment_date or hire_date")


class RAGParams(BaseModel):
    """RAG search parameters"""
    k: int = Field(default=5, description="Number of results requested")
    similarity_threshold: float = Field(default=0.0, description="Similarity threshold used")
    context_found: int = Field(default=0, description="Number of contexts found")


class RAGMetrics(BaseModel):
    """RAG performance metrics"""
    response_time_ms: float = Field(..., description="Time to generate response in milliseconds")
    answer_length: int = Field(default=0, description="Length of answer text in characters")
    answer_text: str = Field(default="", description="Full answer text from LLM")
    success: bool = Field(default=True, description="Whether query was successful")


class QueryMetadata(BaseModel):
    """Additional query metadata"""
    model_used: str = Field(default="gemini-2.5-flash", description="LLM model used")
    history_used: bool = Field(default=False, description="Whether chat history was used")
    history_count: int = Field(default=0, description="Number of history messages used")
    query_rewritten: bool = Field(default=False, description="Whether query was rewritten")


class QueryLog(BaseModel):
    """
    Model for individual query logs (RESTRUCTURED)
    Stores each user query with nested metadata for better organization
    """
    query_id: str = Field(..., description="Unique query identifier (UUID)")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Query timestamp (UTC)")
    
    # Nested objects
    user: UserInfo = Field(..., description="User information")
    session_id: str = Field(..., description="Session identifier")
    
    query_text: str = Field(..., description="Original user query")
    rewritten_query: Optional[str] = Field(None, description="Query after rewriting (if applicable)")
    
    rag_params: RAGParams = Field(..., description="RAG search parameters")
    rag_metrics: RAGMetrics = Field(..., description="RAG performance metrics")
    metadata: QueryMetadata = Field(..., description="Additional metadata")
    
    class Config:
        json_schema_extra = {
            "example": {
                "query_id": "550e8400-e29b-41d4-a716-446655440000",
                "timestamp": "2025-12-09T07:35:00Z",
                "user": {
                    "user_id": 1005,
                    "user_type": "Học sinh",
                    "department_id": 104,
                    "department_name": "Khoa Công nghệ Thông tin",
                    "code": "K21.YDUOC.001",
                    "years": 4
                },
                "session_id": "usr:1005:sess:1733720100:abcd1234",
                "query_text": "Python là gì?",
                "rewritten_query": None,
                "rag_params": {
                    "k": 5,
                    "similarity_threshold": 0.0,
                    "context_found": 5
                },
                "rag_metrics": {
                    "response_time_ms": 1234.56,
                    "answer_length": 512,
                    "answer_text": "Python là một ngôn ngữ lập trình...",
                    "success": True
                },
                "metadata": {
                    "model_used": "gemini-2.5-flash",
                    "history_used": False,
                    "history_count": 0,
                    "query_rewritten": False
                }
            }
        }


class QueryAnalytics(BaseModel):
    """
    Model for aggregated query analytics
    Generated by Spark Streaming from QueryLog events
    """
    # Window information
    window_start: datetime = Field(..., description="Aggregation window start time")
    window_end: datetime = Field(..., description="Aggregation window end time")
    
    # Dimensions
    faculty: Optional[str] = Field(None, description="Faculty name (if grouped by faculty)")
    year: Optional[str] = Field(None, description="Academic year (if grouped by year)")
    file_type: Optional[str] = Field(None, description="Document type (if grouped by file_type)")
    
    # Metrics
    query_count: int = Field(default=0, description="Number of queries in window")
    unique_users: int = Field(default=0, description="Count of unique users")
    avg_response_time: float = Field(default=0.0, description="Average response time in ms")
    avg_contexts_found: float = Field(default=0.0, description="Average number of contexts found")
    
    # Query characteristics
    rewritten_queries: int = Field(default=0, description="Number of queries that were rewritten")
    history_used_count: int = Field(default=0, description="Number of queries using history")
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Analytics record creation time")
    
    class Config:
        json_schema_extra = {
            "example": {
                "window_start": "2025-12-07T15:00:00Z",
                "window_end": "2025-12-07T15:05:00Z",
                "faculty": "CNTT",
                "year": "2025",
                "file_type": "public",
                "query_count": 42,
                "unique_users": 15,
                "avg_response_time": 1234.56,
                "avg_contexts_found": 4.8,
                "rewritten_queries": 18,
                "history_used_count": 25,
                "created_at": "2025-12-07T15:05:01Z"
            }
        }


class RealtimeMetrics(BaseModel):
    """
    Model for real-time metrics response
    Used by analytics API endpoints
    """
    total_queries: int = Field(..., description="Total queries in time period")
    unique_users: int = Field(..., description="Unique users count")
    avg_response_time: float = Field(..., description="Average response time in ms")
    most_active_faculty: str = Field(..., description="Faculty with most queries")
    queries_per_minute: float = Field(..., description="Average queries per minute")
    time_range_minutes: int = Field(..., description="Time range of metrics in minutes")
    
    class Config:
        json_schema_extra = {
            "example": {
                "total_queries": 150,
                "unique_users": 45,
                "avg_response_time": 1245.67,
                "most_active_faculty": "CNTT",
                "queries_per_minute": 2.5,
                "time_range_minutes": 60
            }
        }


class FacultyQueryStats(BaseModel):
    """Faculty-level query statistics"""
    faculty: str
    query_count: int
    unique_users: int
    avg_response_time: float
    percentage: float  # Percentage of total queries


class YearQueryStats(BaseModel):
    """Year-level query statistics"""
    year: str
    query_count: int
    unique_users: int
    avg_response_time: float
    percentage: float  # Percentage of total queries


class HeatmapData(BaseModel):
    """
    Heatmap data for faculty-year query distribution
    """
    faculty: str
    year: str
    query_count: int
    avg_response_time: float


class TimeSeriesPoint(BaseModel):
    """Time series data point"""
    timestamp: datetime
    value: float
    label: Optional[str] = None
