# app/models.py
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


class FileType(str, Enum):
    """Enum for file types"""
    PUBLIC = "public"
    STUDENT = "student"
    TEACHER = "teacher"
    ADMIN = "admin"


class QueryLog(BaseModel):
    """
    Model for individual query logs
    Stores each user query with metadata for tracking and analytics
    """
    query_id: str = Field(..., description="Unique query identifier (UUID)")
    user_id: str = Field(..., description="User ID from JWT token")
    session_id: str = Field(..., description="Session identifier")
    query_text: str = Field(..., description="Original user query")
    rewritten_query: Optional[str] = Field(None, description="Query after rewriting (if applicable)")
    
    # User context
    faculty: str = Field(default="Unknown", description="User's faculty/department")
    year: str = Field(default="Unknown", description="Academic year (e.g., '2025', 'Graduate')")
    
    # Query details
    file_type: str = Field(..., description="Document type queried")
    k: int = Field(default=5, description="Number of results requested")
    
    # Performance metrics
    response_time_ms: float = Field(..., description="Time to generate response in milliseconds")
    contexts_found: int = Field(default=0, description="Number of relevant contexts found")
    similarity_threshold: float = Field(default=0.0, description="Similarity threshold used")
    
    # Query status
    query_rewritten: bool = Field(default=False, description="Whether query was rewritten")
    history_used: bool = Field(default=False, description="Whether chat history was used")
    history_count: int = Field(default=0, description="Number of history messages used")
    
    # Timestamp
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Query timestamp (UTC)")
    
    class Config:
        # Allow MongoDB _id field
        json_schema_extra = {
            "example": {
                "query_id": "550e8400-e29b-41d4-a716-446655440000",
                "user_id": "123",
                "session_id": "usr:123:sess:1234567890:abcd1234",
                "query_text": "Python là gì?",
                "rewritten_query": None,
                "faculty": "CNTT",
                "year": "2025",
                "file_type": "public",
                "k": 5,
                "response_time_ms": 1245.67,
                "contexts_found": 5,
                "similarity_threshold": 0.0,
                "query_rewritten": False,
                "history_used": False,
                "history_count": 0,
                "timestamp": "2025-12-07T15:00:00Z"
            }
        }


class QueryAnalytics(BaseModel):
    """
    Model for aggregated query analytics
    Generated by Spark Streaming from QueryLog events
    """
    # Window information
    window_start: datetime = Field(..., description="Aggregation window start time")
    window_end: datetime = Field(..., description="Aggregation window end time")
    
    # Dimensions
    faculty: Optional[str] = Field(None, description="Faculty name (if grouped by faculty)")
    year: Optional[str] = Field(None, description="Academic year (if grouped by year)")
    file_type: Optional[str] = Field(None, description="Document type (if grouped by file_type)")
    
    # Metrics
    query_count: int = Field(default=0, description="Number of queries in window")
    unique_users: int = Field(default=0, description="Count of unique users")
    avg_response_time: float = Field(default=0.0, description="Average response time in ms")
    avg_contexts_found: float = Field(default=0.0, description="Average number of contexts found")
    
    # Query characteristics
    rewritten_queries: int = Field(default=0, description="Number of queries that were rewritten")
    history_used_count: int = Field(default=0, description="Number of queries using history")
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Analytics record creation time")
    
    class Config:
        json_schema_extra = {
            "example": {
                "window_start": "2025-12-07T15:00:00Z",
                "window_end": "2025-12-07T15:05:00Z",
                "faculty": "CNTT",
                "year": "2025",
                "file_type": "public",
                "query_count": 42,
                "unique_users": 15,
                "avg_response_time": 1234.56,
                "avg_contexts_found": 4.8,
                "rewritten_queries": 18,
                "history_used_count": 25,
                "created_at": "2025-12-07T15:05:01Z"
            }
        }


class RealtimeMetrics(BaseModel):
    """
    Model for real-time metrics response
    Used by analytics API endpoints
    """
    total_queries: int = Field(..., description="Total queries in time period")
    unique_users: int = Field(..., description="Unique users count")
    avg_response_time: float = Field(..., description="Average response time in ms")
    most_active_faculty: str = Field(..., description="Faculty with most queries")
    queries_per_minute: float = Field(..., description="Average queries per minute")
    time_range_minutes: int = Field(..., description="Time range of metrics in minutes")
    
    class Config:
        json_schema_extra = {
            "example": {
                "total_queries": 150,
                "unique_users": 45,
                "avg_response_time": 1245.67,
                "most_active_faculty": "CNTT",
                "queries_per_minute": 2.5,
                "time_range_minutes": 60
            }
        }


class FacultyQueryStats(BaseModel):
    """Faculty-level query statistics"""
    faculty: str
    query_count: int
    unique_users: int
    avg_response_time: float
    percentage: float  # Percentage of total queries


class YearQueryStats(BaseModel):
    """Year-level query statistics"""
    year: str
    query_count: int
    unique_users: int
    avg_response_time: float
    percentage: float  # Percentage of total queries


class HeatmapData(BaseModel):
    """
    Heatmap data for faculty-year query distribution
    """
    faculty: str
    year: str
    query_count: int
    avg_response_time: float


class TimeSeriesPoint(BaseModel):
    """Time series data point"""
    timestamp: datetime
    value: float
    label: Optional[str] = None
